### PR TITLE
fix: build with psycopg2 from source

### PR DESCRIPTION
**Pull request by SteveHNH**
Inside the govcloud environment, all apps must run with fips compliance. The psycopg2-binary does not contain what it needs to run in a FIPS environment. To fix this, we need to compile psycopg2 from source when we build the image.

This was done wiht host-inventory successfully, so we're going through other apps with a similar setup and fixing the image to run properly. This shouldn't effect the way the app runs in other environments.

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by jpramos123 — APPROVED** [review]
LGTM!

@petrblaho Can you also take a look?

Thanks

**Review by jpramos123 — CHANGES_REQUESTED** [review]
Overall, this LGTM!

Please, just make sure you run the manifest script: https://github.com/RedHatInsights/historical-system-profiles-backend/blob/master/scripts/create-manifest.py

And resubmit the commit!

This will make Travis CI to pass without issues

**Review by jpramos123 — APPROVED** [review]

**Review by fellipeh — APPROVED** [review]
lgtm

**Comment by SteveHNH** [comment]
@jpramos123 @fellipeh @petrblaho with all the approvals can we get a merge on this one?

**Comment by petrblaho** [comment]
> @jpramos123 @fellipeh @petrblaho with all the approvals can we get a merge on this one?

I am approving this.

I have few questions though:

- Is this task being tracked in jira we all can access? If you could, please, post jira ID or link here
- Is there similar work planned for https://github.com/RedHatInsights/system-baseline-backend ?
- Where can I find more information about running unit tests in container? Ie. why we need this [`efff4d3` (#287)](https://github.com/RedHatInsights/historical-system-profiles-backend/pull/287/commits/efff4d301cbd6fdee1fb8162af9553c4f1f278d7) commit?

Thank you for your work and contribution here in Drift app :-)

**Review by petrblaho — APPROVED** [review]

**Comment by SteveHNH** [comment]
@petrblaho I added the JIRA card to the description of this pr, and the one for system-baselines-backend.
As far as the tests in a container, I copied much of this from work that @bsquizz did from inventory. I'm not sure we have anything documented that I'm aware of. As far as what it _does_, it sets up containers for the database and app and networks them together so we don't have to have external databases configured for testing. I think that's the main gain from it.

**Pull request merged**
