### PR TITLE
Bump kerlescan, update dependencies

### PR DESCRIPTION
**Pull request by CodeHeeler**
## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by petrblaho** [comment]
Shouldn't we lock flask version the same way as with https://github.com/RedHatInsights/drift-backend/pull/263#issuecomment-853385775 ?

**Comment by CodeHeeler** [comment]
> Shouldn't we lock flask version the same way as with [RedHatInsights/drift-backend#263 (comment)](https://github.com/RedHatInsights/drift-backend/pull/263#issuecomment-853385775) ?

No, hsp doesn't rely on insights-core so it does not have this same conflict.  So the only reason to do so would be consistency, but as separate microservices, we already do not force shared dependencies (like insights-core for instance).  They are standalone in this regard.

**Comment by petrblaho** [comment]
> > Shouldn't we lock flask version the same way as with [RedHatInsights/drift-backend#263 (comment)](https://github.com/RedHatInsights/drift-backend/pull/263#issuecomment-853385775) ?
> 
> No, hsp doesn't rely on insights-core so it does not have this same conflict. So the only reason to do so would be consistency, but as separate microservices, we already do not force shared dependencies (like insights-core for instance). They are standalone in this regard.

And deps of kerlescan? https://github.com/RedHatInsights/kerlescan/blob/master/Pipfile#L18

**Comment by CodeHeeler** [comment]
> > > Shouldn't we lock flask version the same way as with [RedHatInsights/drift-backend#263 (comment)](https://github.com/RedHatInsights/drift-backend/pull/263#issuecomment-853385775) ?
> > 
> > 
> > No, hsp doesn't rely on insights-core so it does not have this same conflict. So the only reason to do so would be consistency, but as separate microservices, we already do not force shared dependencies (like insights-core for instance). They are standalone in this regard.
> 
> And deps of kerlescan? https://github.com/RedHatInsights/kerlescan/blob/master/Pipfile#L18

My understanding from talking it over with Beav was that the reason we include insights-core is specifically for parsing RPM versions which is not done in HSP.  This usage is completely unrelated to our use of inventory api or anything, it's only for that one aspect.

**Comment by petrblaho** [comment]
> > > > Shouldn't we lock flask version the same way as with [RedHatInsights/drift-backend#263 (comment)](https://github.com/RedHatInsights/drift-backend/pull/263#issuecomment-853385775) ?
> > > 
> > > 
> > > No, hsp doesn't rely on insights-core so it does not have this same conflict. So the only reason to do so would be consistency, but as separate microservices, we already do not force shared dependencies (like insights-core for instance). They are standalone in this regard.
> > 
> > 
> > And deps of kerlescan? [https://github.com/RedHatInsights/kerlescan/blob/master/Pipfile#L18](https://github.com/RedHatInsights/kerlescan/blob/master/Pipfile?rgh-link-date=2021-06-03T19%3A25%3A21Z#L18)
> 
> My understanding from talking it over with Beav was that the reason we include insights-core is specifically for parsing RPM versions which is not done in HSP. This usage is completely unrelated to our use of inventory api or anything, it's only for that one aspect.

Ok, makes sense. I would still prefer if we would have the same versions with all of our services as different versions can confuse as when looking for a bug unless we really need newer one here.

I will let you decide, acking :-)

**Review by petrblaho — APPROVED** [review]

**Comment by CodeHeeler** [comment]
> > > > > Shouldn't we lock flask version the same way as with [RedHatInsights/drift-backend#263 (comment)](https://github.com/RedHatInsights/drift-backend/pull/263#issuecomment-853385775) ?
> > > > 
> > > > 
> > > > No, hsp doesn't rely on insights-core so it does not have this same conflict. So the only reason to do so would be consistency, but as separate microservices, we already do not force shared dependencies (like insights-core for instance). They are standalone in this regard.
> > > 
> > > 
> > > And deps of kerlescan? [https://github.com/RedHatInsights/kerlescan/blob/master/Pipfile#L18](https://github.com/RedHatInsights/kerlescan/blob/master/Pipfile?rgh-link-date=2021-06-03T19%3A25%3A21Z#L18)
> > 
> > 
> > My understanding from talking it over with Beav was that the reason we include insights-core is specifically for parsing RPM versions which is not done in HSP. This usage is completely unrelated to our use of inventory api or anything, it's only for that one aspect.
> 
> Ok, makes sense. I would still prefer if we would have the same versions with all of our services as different versions can confuse as when looking for a bug unless we really need newer one here.
> 
> I will let you decide, acking :-)

Ok, spoke with beav who said maybe there's a way to have one repo with all code so that they all have the same Pipfiles, dependencies, etc (bonus of not needing to worry about kerlescan versions anymore by rolling it in), but then still deploy them as 3 separate services perhaps? and I mentioned the db issues we've had recently where 1 db would make more sense.  I'm going to merge this for now, but add this to our discussion list for our meeting to consider a refactor of the code.

**Pull request merged**
